// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8hXTUnO67dryOyZ5fxNlxTxihxy3Ttuw',
    appId: '1:878238233412:web:9481143f5c790374df5d11',
    messagingSenderId: '878238233412',
    projectId: 'rally-c6299',
    authDomain: 'rally-c6299.firebaseapp.com',
    storageBucket: 'rally-c6299.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFa7z0RR5vdHEdhPW0KLtetppA8-a9RJY',
    appId: '1:878238233412:android:ddb2bfe4bdf1e079df5d11',
    messagingSenderId: '878238233412',
    projectId: 'rally-c6299',
    storageBucket: 'rally-c6299.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBJNoJBG_BMAqDdQkLMTr2OZhpGIZ9A5Q',
    appId: '1:878238233412:ios:090bb7283c978ea5df5d11',
    messagingSenderId: '878238233412',
    projectId: 'rally-c6299',
    storageBucket: 'rally-c6299.firebasestorage.app',
    iosBundleId: 'com.example.rally',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBJNoJBG_BMAqDdQkLMTr2OZhpGIZ9A5Q',
    appId: '1:878238233412:ios:090bb7283c978ea5df5d11',
    messagingSenderId: '878238233412',
    projectId: 'rally-c6299',
    storageBucket: 'rally-c6299.firebasestorage.app',
    iosBundleId: 'com.example.rally',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8hXTUnO67dryOyZ5fxNlxTxihxy3Ttuw',
    appId: '1:878238233412:web:78903c518661de01df5d11',
    messagingSenderId: '878238233412',
    projectId: 'rally-c6299',
    authDomain: 'rally-c6299.firebaseapp.com',
    storageBucket: 'rally-c6299.firebasestorage.app',
  );
}
